Controllers/ManageCareGiversController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace HospitalManagament.Controllers
{
    public class ManageCareGiversController : Controller
    {
        private HospitalManagementContext db = new HospitalManagementContext();

        // GET: ManageCareGivers
        public ActionResult Index()
        {
            var users = db.Users.Include(u => u.Caregiver);
            return View(users.ToList().Where(x => x.UserName != "Admin").Where(x => x.Caregiver != null));
        }

        // GET: ManageCareGivers/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: ManageCareGivers/Create
        public ActionResult Create()
        {
            User user = new User();
            user.Patient = new Patient();

            ViewBag.PatientId = new SelectList(db.Patients.Include(a => a.User).Select(a => new { a.User.FullName, a.Id }), "Id", "FullName");
            return View(user);
        }

        // POST: ManageCareGivers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {
                // add careGiver
                Caregiver caregiver = new Caregiver();
                
                // add role as caregiver 
                user.Role = db.Roles.ToList().Where(u => u.Name == "Caregiver").FirstOrDefault();
                user.Salt = HomeController.GenerateRandomString(10);
                user.Password = Crypto.SHA256(user.Password + user.Salt);
                user.Caregiver = caregiver;
                user.IsLogin = false;
                user.IsEnabled = true;
                user.LoginAttemptCount = 0;

                db.Users.Add(user);

                db.SaveChanges();

                User newUser = db.Users.ToList().Last();

                User Admin = (User)HttpContext.Session["LoggedInUser"];

                // Update totals count 
                if (Admin != null && Admin.Role.Name == "Admin")
                {
                    HttpContext.Session["TotalPatientList"] = db.Users.Include(u => u.Patient).Where(u => u.Patient != null).Where(u => u.Patient.Status == "Admitted").ToList();
                    HttpContext.Session["TotalPatients"] = db.Users.Count(u => u.Patient != null && u.Patient.Status == "Admitted");
                    HttpContext.Session["TotalCaregiverList"] = db.Users.Include(u => u.Caregiver).Where(u => u.Caregiver != null).ToList();
                    HttpContext.Session["TotalCareGivers"] = db.Users.Count(u => u.Caregiver != null);
                    HttpContext.Session["TotalDoctorList"] = db.Users.Include(u => u.Doctor).Where(u => u.Doctor != null).ToList();
                    HttpContext.Session["TotalDoctors"] = db.Users.Count(u => u.Doctor != null);
                    HttpContext.Session["RecetlyRegisteredUserList"] = db.Users.OrderByDescending(u => u.Id).Take(10).ToList();
                    HttpContext.Session["TotalLoginUsers"] = db.Users.Count(u => u.IsLogin != null && u.IsLogin == true);
                    HttpContext.Session["TotalLogoutUsers"] = db.Users.Count(u => u.IsLogin == null || u.IsLogin == false);
                    HttpContext.Session["TotalInactive"] = db.Users.Count(u => (u.IsLogin == null || u.IsLogin == false) && u.LastLogin != null && DbFunctions.DiffDays(u.LastLogin.Value, DateTime.Now) > 1);
                }

                return RedirectToAction("Index");
            }

            ViewBag.PatientId = new SelectList(db.Patients.Include(a => a.User).Select(a => new { a.User.FullName, a.Id }), "Id", "FullName");
            return View(user);
        }

        // GET: ManageCareGivers/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            Caregiver careGiver = user.Caregiver;
            if (careGiver == null)
            {
                return HttpNotFound();
            }
            // Fetch all patients
            ViewBag.PatientId = new SelectList(db.Patients.Include(a => a.User).Select(a => new { a.User.FullName, a.Id }), "Id", "FullName", 2);
            return View(db.Users.FirstOrDefault(a => a.Id == id));
        }

        // POST: ManageCareGivers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                User oldUser = db.Users.FirstOrDefault(u => u.Id == user.Id);

                oldUser.FullName = user.FullName;
                oldUser.UserName = user.UserName;
                oldUser.NRIC = user.NRIC;
                oldUser.Age = user.Age;
                oldUser.ContactNo = user.ContactNo;
                oldUser.Email = user.Email;
                oldUser.Gender = user.Gender;
                oldUser.Address = user.Address;
                oldUser.Comments = user.Comments;
                
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                foreach (ModelState modelState in ViewData.ModelState.Values)
                {
                    foreach (ModelError error in modelState.Errors)
                    {
                        System.Diagnostics.Debug.WriteLine(error);
                        if(error.ErrorMessage == "The Id field is required.")
                        {
                            User oldUser = db.Users.FirstOrDefault(u => u.Id == user.Id);

                            oldUser.FullName = user.FullName;
                            oldUser.UserName = user.UserName;
                            oldUser.NRIC = user.NRIC;
                            oldUser.Age = user.Age;
                            oldUser.ContactNo = user.ContactNo;
                            oldUser.Email = user.Email;
                            oldUser.Gender = user.Gender;
                            oldUser.Address = user.Address;
                            oldUser.Comments = user.Comments;
                            
                            db.SaveChanges();

                            return RedirectToAction("Index");
                        }
                    }
                }

                var errors = ModelState.Select(x => x.Value.Errors)
                           .Where(y => y.Count > 0)
                           .ToList();
                System.Diagnostics.Debug.WriteLine(errors);
            }

            ViewBag.PatientId = new SelectList(db.Patients.Include(a => a.User).Select(a => new { a.User.FullName, a.Id }), "Id", "FullName", 2);
            return View(user);
        }

        // GET: ManageCareGivers/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: ManageCareGivers/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(long id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            User user = db.Users.Find(id);

            if (user == null)
            {
                return HttpNotFound();
            }

            user.Caregiver.Patient = null;

            db.Caregivers.Remove(user.Caregiver);

            db.Users.Remove(user);

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/ManageCareGivers/Create.cshtml
@model HospitalManagament.User

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="white-box">
    <div class="row">
        <div class="col-sm-12 col-xs-12">
            @using (Html.BeginForm("Create", "ManageCareGivers", FormMethod.Post,
                             new { enctype = "multipart/form-data", data_toggle = "validator" }))
            {
                <div class="form-group">
                    <label for="exampleInputEmail1" class="control-label">Full Name</label>
                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Email</label>
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @required = "required", @type = "email" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Password</label>
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @required = "required", @type = "password" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">NRIC</label>
                    @Html.EditorFor(model => model.NRIC, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.NRIC, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Age</label>
                    @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">ContactNo</label>
                    @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                </div>
                @*<div class="form-group">
                        <label for="exampleInputPassword1">Occupation</label>
                        @Html.EditorFor(model => model.Occupation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Occupation, "", new { @class = "text-danger" })
                    </div>*@

                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Gender</label>
                    <div>
                        <label class="radio-inline">
                            @Html.RadioButtonFor(u => u.Gender, "Male", new { @class = "form-control", @checked = true, @id = "Male" })
                        </label> <label for="Male">Male</label>
                        <label class="radio-inline">
                            @Html.RadioButtonFor(u => u.Gender, "Female", new { @class = "form-control", @id = "Female" })
                        </label> <label for="Female">Female</label>
                    </div>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Address</label>
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Id, "Patient", htmlAttributes: new { @class = "control-label col-md-2 control-label" })
                    @Html.DropDownList("PatientId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Profile Description</label>
                    @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                </div>
                <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Create</button>
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success waves-effect waves-light m-r-10" })
            }
        </div>
    </div>
</div>

Views/ManageCareGivers/Delete.cshtml
@model HospitalManagament.User

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="white-box">
    <h3>Are you sure you want to delete this?</h3>
    <div class="row">
        <div class="col-md-4 col-xs-12">
            <div class="white-box">
                <div class="user-bg"> <img alt="user" src="~/plugins/images/big/img2.jpg" width="100%"> </div>
                <div class="user-btm-box">
                    <!-- .row -->
                    <div class="row text-center m-t-10">
                        <div class="col-md-6 b-r">
                            <strong>Name</strong>
                            <p>@Model.UserName</p>
                        </div>
                        <div class="col-md-6">
                            <strong>Occupation</strong>
                            <p>Care Giver</p>
                        </div>
                    </div>
                    <!-- /.row -->
                    <hr>
                    <!-- .row -->
                    <div class="row text-center m-t-10">
                        <div class="col-md-6 b-r">
                            <strong>Email ID</strong>
                            <p>@Model.Email</p>
                        </div>
                        <div class="col-md-6">
                            <strong>Phone</strong>
                            <p>@Model.ContactNo</p>
                        </div>
                    </div>
                    <!-- /.row -->
                    <hr>
                    <!-- .row -->
                    <div class="row text-center m-t-10">
                        <div class="col-md-12">
                            <strong>Address</strong>
                            <p>
                                @Model.Address
                            </p>
                        </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
        <div class="col-md-8 col-xs-12">
            <div class="white-box">
                <div class="row">
                    <div class="col-md-3 col-xs-6 b-r">
                        <strong>Full Name</strong>
                        <br>
                        <p class="text-muted">@Model.FullName</p>
                    </div>
                    <div class="col-md-3 col-xs-6 b-r">
                        <strong>Mobile</strong>
                        <br>
                        <p class="text-muted">@Model.ContactNo</p>
                    </div>
                    <div class="col-md-3 col-xs-6 b-r">
                        <strong>Email</strong>
                        <br>
                        <p class="text-muted">@Model.Email</p>
                    </div>
                </div>
                <hr>
                <p class="m-t-30">
                    @Model.Comments
                </p>
            </div>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/ManageCareGivers/Details.cshtml
@model HospitalManagament.User

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="white-box">
    <div class="row">
        <div class="col-md-4 col-xs-12">
            <div class="white-box">
                <div class="user-bg"> <img alt="user" src="~/plugins/images/big/img3.jpg" width="100%"> </div>
                <div class="user-btm-box">
                    <!-- .row -->
                    <div class="row text-center m-t-10">
                        <div class="col-md-6 b-r">
                            <strong>Name</strong>
                            <p>@Model.UserName</p>
                        </div>
                        <div class="col-md-6">
                            <strong>Occupation</strong>
                            <p>Care Giver</p>
                        </div>
                    </div>
                    <!-- /.row -->
                    <hr>
                    <!-- .row -->
                    <div class="row text-center m-t-10">
                        <div class="col-md-6 b-r">
                            <strong>Email ID</strong>
                            <p>@Model.Email</p>
                        </div>
                        <div class="col-md-6">
                            <strong>Phone</strong>
                            <p>@Model.ContactNo</p>
                        </div>
                    </div>
                    <!-- /.row -->
                    <hr>
                    <!-- .row -->
                    <div class="row text-center m-t-10">
                        <div class="col-md-12">
                            <strong>Address</strong>
                            <p>
                                @Model.Address
                            </p>
                        </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
        <div class="col-md-8 col-xs-12">
            <div class="white-box">
                <div class="row">
                    <div class="col-md-3 col-xs-6 b-r">
                        <strong>Full Name</strong>
                        <br>
                        <p class="text-muted">@Model.FullName</p>
                    </div>
                    <div class="col-md-3 col-xs-6 b-r">
                        <strong>Mobile</strong>
                        <br>
                        <p class="text-muted">@Model.ContactNo</p>
                    </div>
                    <div class="col-md-3 col-xs-6 b-r">
                        <strong>Email</strong>
                        <br>
                        <p class="text-muted">@Model.Email</p>
                    </div>
                </div>
                <hr>
                <p class="m-t-30">
                    @Model.Comments
                </p>
            </div>
        </div>

    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

Views/ManageCareGivers/Edit.cshtml
@model HospitalManagament.User

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="white-box">
    <div class="row">
        <div class="col-sm-12 col-xs-12">
            @using (Html.BeginForm("Edit", "ManageCareGivers", FormMethod.Post,
                             new { enctype = "multipart/form-data", data_toggle = "validator" }))
            {
                <div class="form-group">
                    @Html.HiddenFor(a => a.Id)
                    @Html.HiddenFor(a => a.Caregiver.Id)
                    @Html.HiddenFor(a => a.Caregiver.Patient.Id)
                    <label for="exampleInputEmail1" class="control-label">Full Name</label>
                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">NRIC</label>
                    @Html.EditorFor(model => model.NRIC, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.NRIC, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Age</label>
                    @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">ContactNo</label>
                    @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Gender</label>
                    <div>
                        <label class="radio-inline">
                            @Html.RadioButtonFor(u => u.Gender, "Male", new { @class = "form-control", @checked = true, @id = "Male" })
                        </label> <label for="Male">Male</label>
                        <label class="radio-inline">
                            @Html.RadioButtonFor(u => u.Gender, "Female", new { @class = "form-control", @id = "Female" })
                        </label> <label for="Female">Female</label>
                    </div>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Address</label>
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Patient.Id, "Patient", htmlAttributes: new { @class = "control-label col-md-2 control-label" })
                    @Html.DropDownList("PatientId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Patient.Id, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Profile Description</label>
                    @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                </div>
                <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Save</button>
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success waves-effect waves-light m-r-10" })
            }
        </div>
    </div>
</div>

Views/ManageCareGivers/Index.cshtml
@model IEnumerable<HospitalManagament.User>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="white-box">
    <div style="margin-bottom: 15px;">
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-success waves-effect waves-light m-r-10" })
    </div>

    <div class="table-responsive">
        <table id="myTable" class="table table-striped">
            <thead>
                <tr>
                    <th>FullName</th>
                    <th>Username</th>
                    <th>Age</th>
                    <th>ContactNo</th>
                    <th>
                        Email
                    </th>
                    <th class="no-sort">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UserName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Age)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ContactNo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


<script>
    $(document).ready(function () {
    $('#myTable').DataTable({dom: 'Bfrtip',
        buttons: [
            'pdf', 'print'
        ]});
    });

</script>
<!--Style Switcher -->
<script src="../plugins/bower_components/styleswitcher/jQuery.style.switcher.js"></script>