Controllers/ManageEventsController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace HospitalManagament.Controllers
{
    public class ManageEventsController : Controller
    {
        private HospitalManagementContext db = new HospitalManagementContext();

        // GET: ManageEvents
        public ActionResult Index()
        {
            // Get logged in user
            User user = (User)HttpContext.Session["LoggedInUser"];

            if(user != null && (user.Role.Name == "Admin" || user.Role.Name == "Doctor"))
            {
                var events = db.Events.ToList().Where(e => e.UserId == user.Id);
                return View(events);
            }

            return HttpNotFound();            
        }

        // GET: ManageEvents/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event event1 = db.Events.Find(id);
            if (event1 == null)
            {
                return HttpNotFound();
            }
            return View(event1);
        }

        // GET: ManageEvents/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ManageEvents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(Event event1)
        {
            if (ModelState.IsValid)
            {
                // Add date and time
                var StartDate = DateTime.ParseExact(event1.StartDateStr, "MM/dd/yyyy", CultureInfo.InvariantCulture);

                event1.Start = new DateTime(StartDate.Year, StartDate.Month, StartDate.Day, event1.StartTime.Value.Hours, event1.StartTime.Value.Minutes, event1.StartTime.Value.Seconds);

                var EndDate = DateTime.ParseExact(event1.EndDateStr, "MM/dd/yyyy", CultureInfo.InvariantCulture);

                event1.End = new DateTime(EndDate.Year, EndDate.Month, EndDate.Day, event1.EndTime.Value.Hours, event1.EndTime.Value.Minutes, event1.EndTime.Value.Seconds);

                // Create url

                User user = (User)HttpContext.Session["LoggedInUser"];

                event1.User = db.Users.ToList().Where(u => u.Id == user.Id).FirstOrDefault();

                db.Events.Add(event1);

                db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(event1);
        }

        // GET: ManageEvents/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event event1 = db.Events.Find(id);
            if (event1 == null)
            {
                return HttpNotFound();
            }
            return View(event1);
        }

        // POST: ManageEvents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit(Event event1)
        {
            if (ModelState.IsValid)
            {
                // Get logged in user
                User user = (User)HttpContext.Session["LoggedInUser"];

                Event oldEvent = db.Events.FirstOrDefault(e => e.Id == event1.Id);

                var StartDate = DateTime.ParseExact(event1.StartDateStr, "MM/dd/yyyy", CultureInfo.InvariantCulture);

                event1.Start = new DateTime(StartDate.Year, StartDate.Month, StartDate.Day, event1.StartTime.Value.Hours, event1.StartTime.Value.Minutes, event1.StartTime.Value.Seconds);

                var EndDate = DateTime.ParseExact(event1.EndDateStr, "MM/dd/yyyy", CultureInfo.InvariantCulture);

                event1.End = new DateTime(EndDate.Year, EndDate.Month, EndDate.Day, event1.EndTime.Value.Hours, event1.EndTime.Value.Minutes, event1.EndTime.Value.Seconds);

                oldEvent.Name = event1.Name;
                oldEvent.Description = event1.Description;
                oldEvent.allDay = event1.allDay;
                oldEvent.End = event1.End;
                oldEvent.EndDateStr = event1.EndDateStr;
                oldEvent.EndTime = event1.EndTime;
                oldEvent.Start = event1.Start;
                oldEvent.StartDateStr = event1.StartDateStr;
                oldEvent.StartTime = event1.StartTime;
                oldEvent.Status = event1.Status;

                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(event1);
        }

        // GET: ManageEvents/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Event event1 = db.Events.Find(id);
            if (event1 == null)
            {
                return HttpNotFound();
            }

            db.Events.Remove(event1);

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // POST: ManageEvents/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(long id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Event event1 = db.Events.Find(id);
            if (event1 == null)
            {
                return HttpNotFound();
            }

            db.Events.Remove(event1);

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // Fetch All event for loggedin user
        [HttpGet]
        public ActionResult AllEvents()
        {
            User user = (User)HttpContext.Session["LoggedInUser"];

            List<Event> allEvents = new List<Event>();

            if (user != null)
            {
                HospitalManagementContext db = new HospitalManagementContext();

                allEvents = db.Database.SqlQuery<Event>("select * from [dbo].Events e where e.UserId = " + user.Id).ToList();

                //allEvents = (List<Event>) db.Events.ToList().Where(e => e.UserId == user.Id);
            }

            return Content(JsonConvert.SerializeObject(allEvents), "application/json");
        }
    }
}

Views/Doctor/Edit.cshtml
@model HospitalManagament.User

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="white-box">
    <div class="row">
        <div class="col-sm-12 col-xs-12">
            @using (Html.BeginForm("Edit", "Doctor", FormMethod.Post,
                             new { enctype = "multipart/form-data", data_toggle = "validator" }))
            {
                <div class="form-group">
                    @Html.HiddenFor(a => a.Id)
                    @Html.HiddenFor(a => a.Doctor.Id)
                    <label for="exampleInputEmail1" class="control-label">Full Name</label>
                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">NRIC</label>
                    @Html.EditorFor(model => model.NRIC, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.NRIC, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Age</label>
                    @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">ContactNo</label>
                    @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Gender</label>
                    <div>
                        <label class="radio-inline">
                            @Html.RadioButtonFor(u => u.Gender, "Male", new { @class = "form-control", @checked = true, @id = "Male" })
                        </label> <label for="Male">Male</label>
                        <label class="radio-inline">
                            @Html.RadioButtonFor(u => u.Gender, "Female", new { @class = "form-control", @id = "Female" })
                        </label> <label for="Female">Female</label>
                    </div>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Designation</label>
                    @Html.EditorFor(model => model.Doctor.Designation, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Doctor.Designation, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Specialization</label>
                    @Html.EditorFor(model => model.Doctor.Specialization, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Doctor.Specialization, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Address</label>
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Profile Description</label>
                    @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                </div>
                <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Save</button>
                @Html.ActionLink("Profile", "Index", null, new { @class = "btn btn-success waves-effect waves-light m-r-10" })
            }
        </div>
    </div>
</div>

Views/Doctor/Index.cshtml
@model HospitalManagament.User

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h4 class="page-title">Edit Doctor Profile</h4>
<div class="row">
    <div class="col-md-4 col-xs-12">
        <div class="white-box">
            <div class="user-bg"> <img alt="user" src="~/plugins/images/big/img3.jpg" width="100%"> </div>
            <div class="user-btm-box">
                <!-- .row -->
                <div class="row text-center m-t-10">
                    <div class="col-md-6 b-r">
                        <strong>Name</strong>
                        <p>@Model.UserName</p>
                    </div>
                    <div class="col-md-6">
                        <strong>Occupation</strong>
                        <p>Care Giver</p>
                    </div>
                </div>
                <!-- /.row -->
                <hr>
                <!-- .row -->
                <div class="row text-center m-t-10">
                    <div class="col-md-6 b-r">
                        <strong>Email ID</strong>
                        <p>@Model.Email</p>
                    </div>
                    <div class="col-md-6">
                        <strong>Phone</strong>
                        <p>@Model.ContactNo</p>
                    </div>
                </div>
                <!-- /.row -->
                <hr>
                <!-- .row -->
                <div class="row text-center m-t-10">
                    <div class="col-md-12">
                        <strong>Address</strong>
                        <p>
                            @Model.Address
                        </p>
                    </div>
                </div>
                <hr>
            </div>
        </div>
    </div>
    <div class="col-md-8 col-xs-12">
        <div class="white-box">
            <div class="row">
                <div class="col-md-3 col-xs-6 b-r">
                    <strong>Full Name</strong>
                    <br>
                    <p class="text-muted">@Model.FullName</p>
                </div>
                <div class="col-md-3 col-xs-6 b-r">
                    <strong>Mobile</strong>
                    <br>
                    <p class="text-muted">@Model.ContactNo</p>
                </div>
                <div class="col-md-3 col-xs-6 b-r">
                    <strong>Email</strong>
                    <br>
                    <p class="text-muted">@Model.Email</p>
                </div>
                <div class="col-md-3 col-xs-6">
                    <strong>Designation</strong>
                    <br>
                    <p class="text-muted">@Model.Doctor.Designation</p>
                </div>
            </div>
            <hr>
            <p class="m-t-30">
                @Model.Comments
            </p>
        </div>
    </div>

</div>

<div style="margin-bottom: 15px;">
    @Html.ActionLink("Edit", "Edit", "Doctor", new { id = Model.Id }, new { @class = "btn btn-success btn-block" })
</div>

<div class="row">
    <div class="col-md-12">
        <div class="white-box">
            <div id="calendar"></div>
        </div>
    </div>
</div>
<!-- /.modal -->
<div id="event-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 id="event-title" class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <h4>Start</h4>
                <p id="event-start"></p>
                <h4>End</h4>
                <p id="event-end"></p>
                <h4>Description</h4>
                <p id="event-description"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section Scripts
{


    <script>
        // Send ajax call
        $.ajax({
            url: '@Url.Action("AllEvents", "ManageEvents")',
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (data) {
                   
                // Normalize data
                $.each(data, function (index, value) {
                    try {
                        value.start = new Date(value.Start);
                        value.end = new Date(value.End);
                        value.title = value.Description;
                        value.description = value.description;
                    } catch (e) {
                        // Ignore bad data
                    }
                });

                // Append All events

                $('#calendar').fullCalendar({
                    eventClick: function (calEvent, jsEvent, view) {

                        $('#event-title').text(calEvent.title);
                        $('#event-start').text(calEvent.start._d.toLocaleString());
                        $('#event-end').text(calEvent.end._d.toLocaleString());
                        $('#event-description').text(calEvent.description);

                        $('#event-modal').modal('show');

                        // change the border color just for fun
                        $(this).css('border-color', 'red');

                    },
                    header: {
                        left: 'prev,next today',
                        center: 'title',
                        right: 'month,agendaWeek,agendaDay,listWeek'
                    },
                    allDayDefault: false,
                    //editable: true,
                    //droppable: true, // this allows things to be dropped onto the calendar
                    eventLimit: true, // allow "more" link when too many events
                    events: data
                });
            },
            error: function () {
                alert("Error");
            }
        });
    </script>
    
}