Controllers/ManageUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Globalization;
using System.Web.Helpers;

namespace HospitalManagament.Controllers
{
    public class ManageUsersController : Controller
    {
        private HospitalManagementContext db = new HospitalManagementContext();

        // GET: ManagePatients
        public ActionResult Index()
        {
            var users = db.Users.Include(u => u.Caregiver).Include(u => u.Patient);
            return View(users.ToList().Where(x => x.UserName != "Admin"));
        }

        // GET: ManagePatients/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: ManagePatients/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            return View(user);
        }

        // POST: ManagePatients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                User oldUser = db.Users.FirstOrDefault(u => u.Id == user.Id);

                if (oldUser.Email != user.Email)
                {
                    User existingUser = db.Users.FirstOrDefault(u => u.Email == user.Email);

                    if (existingUser != null)
                    {
                        ModelState.AddModelError("", "Email already exists");
                        return View();
                    }
                }

                oldUser.FullName = user.FullName;
                oldUser.UserName = user.UserName;
                oldUser.NRIC = user.NRIC;
                oldUser.Age = user.Age;
                oldUser.ContactNo = user.ContactNo;
                oldUser.Email = user.Email;
                oldUser.Gender = user.Gender;
                oldUser.Address = user.Address;
                oldUser.Comments = user.Comments;

                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: ManagePatients/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            if (user.Role.Name == "Caregiver")
            {
                user.Caregiver.Patient = null;
                db.Caregivers.Remove(user.Caregiver);
            }
            else if (user.Role.Name == "Doctor")
            {
                var doctor = db.Doctors.Include(d => d.Messages).SingleOrDefault(d => d.Id == user.Doctor.Id);

                foreach (var message in doctor.Messages.ToList())
                {
                    db.Messages.Remove(message);
                }

                db.Doctors.Remove(user.Doctor);
            }
            else if (user.Role.Name == "Patient")
            {
                try
                {
                    if (user.Patient.Caregiver != null)
                    {
                        Caregiver caregiver = db.Caregivers.ToList().Where(u => u.Patient.Id == user.Patient.Id).First();
                        caregiver.Patient = null;
                    }
                }
                catch (Exception e)
                {
                }

                var patient = db.Patients.Include(p => p.Messages).SingleOrDefault(p => p.Id == user.Patient.Id);

                foreach(var message in patient.Messages.ToList()) 
                {
                    db.Messages.Remove(message);
                }

                db.Patients.Remove(user.Patient);
            }

            db.Users.Remove(user);

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // POST: ManagePatients/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(long id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/ManageUsers/Delete.cshtml
@model HospitalManagament.User

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="white-box">
    <h3>Are you sure you want to delete this?</h3>
    <div class="row">
        <div class="col-md-4 col-xs-12">
            <div class="white-box">
                <div class="user-bg"> <img alt="user" src="~/plugins/images/big/img2.jpg" width="100%"> </div>
                <div class="user-btm-box">
                    <!-- .row -->
                    <div class="row text-center m-t-10">
                        <div class="col-md-6 b-r">
                            <strong>Name</strong>
                            <p>@Model.UserName</p>
                        </div>
                        <div class="col-md-6">
                            <strong>Occupation</strong>
                            <p>@Model.Patient.Occupation</p>
                        </div>
                    </div>
                    <!-- /.row -->
                    <hr>
                    <!-- .row -->
                    <div class="row text-center m-t-10">
                        <div class="col-md-6 b-r">
                            <strong>Email ID</strong>
                            <p>@Model.Email</p>
                        </div>
                        <div class="col-md-6">
                            <strong>Phone</strong>
                            <p>@Model.ContactNo</p>
                        </div>
                    </div>
                    <!-- /.row -->
                    <hr>
                    <!-- .row -->
                    <div class="row text-center m-t-10">
                        <div class="col-md-12">
                            <strong>Address</strong>
                            <p>
                                @Model.Address
                            </p>
                        </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
        <div class="col-md-8 col-xs-12">
            <div class="white-box">
                <div class="row">
                    <div class="col-md-3 col-xs-6 b-r">
                        <strong>Full Name</strong>
                        <br>
                        <p class="text-muted">@Model.FullName</p>
                    </div>
                    <div class="col-md-3 col-xs-6 b-r">
                        <strong>Mobile</strong>
                        <br>
                        <p class="text-muted">@Model.ContactNo</p>
                    </div>
                    <div class="col-md-3 col-xs-6 b-r">
                        <strong>Email</strong>
                        <br>
                        <p class="text-muted">@Model.Email</p>
                    </div>
                    <div class="col-md-3 col-xs-6">
                        <strong>Disease</strong>
                        <br>
                        <p class="text-muted">@Model.Patient.Disease</p>
                    </div>
                </div>
                <hr>
                <p class="m-t-30">
                    @Model.Comments
                </p>
            </div>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/ManageUsers/Details.cshtml
@model HospitalManagament.User
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="white-box">
    <div class="row">
        <div class="col-xs-12">
            <div class="white-box">
                <div class="user-bg"> <img alt="user" src="~/plugins/images/big/img3.jpg" width="50%" style="margin-left: 25%"> </div>
                <div class="user-btm-box">
                    <!-- .row -->
                    <div class="row text-center m-t-10">
                        <div class="col-md-6 b-r">
                            <strong>Full Name</strong>
                            <p class="text-muted">@Model.FullName</p>
                        </div>
                        <div class="col-md-6">
                            <strong>Email</strong>
                            <p class="text-muted">@Model.Email</p>
                        </div>
                    </div>
                    <!-- /.row -->
                    <hr>
                    <!-- .row -->
                    <div class="row text-center m-t-10">
                        <div class="col-md-6 b-r">
                            <strong>Name</strong>
                            <p>@Model.UserName</p>
                        </div>
                        <div class="col-md-6">
                            <strong>Mobile</strong>
                            <p class="text-muted">@Model.ContactNo</p>
                        </div>
                    </div>
                    <!-- /.row -->
                    <hr>
                    <!-- .row -->
                    <div class="row text-center m-t-10">
                        <div class="col-md-12">
                            <strong>Address</strong>
                            <p>
                                @Model.Address
                            </p>
                        </div>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="white-box">
                <div id="map-canvas" style="width: 100%; height: 480px;"></div>
            </div>
        </div>
    </div>
    @if (Request.Params["param"] == null)
    {
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
    }
</div>
@section Scripts
{
    <!-- Flot Charts JavaScript -->
    <script src="~/plugins/bower_components/flot/jquery.flot.js"></script>
    <script src="~/plugins/bower_components/flot.tooltip/js/jquery.flot.tooltip.min.js"></script>

    <script type="text/javascript">

        function Initialize() {
            var uluru = { lat: 1.290270, lng: 103.851959 };
            var map = new google.maps.Map(document.getElementById('map-canvas'), {
                zoom: 4,
                center: uluru
            });
            var marker = new google.maps.Marker({
                position: uluru,
                map: map
            });
        }
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyB4vOOoEeoAhVDDCjJkbgHKDtQ5MU_3k6c&callback=Initialize"></script>
}

Views/ManageUsers/Edit.cshtml
@model HospitalManagament.User

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="white-box">
    <div class="row">
        <div class="col-sm-12 col-xs-12">
            @using (Html.BeginForm("Edit", "ManageUsers", FormMethod.Post,
                             new { enctype = "multipart/form-data", data_toggle = "validator" }))
            {
                <div class="form-group">
                    @Html.HiddenFor(a => a.Id)
                    <label for="exampleInputEmail1" class="control-label">Full Name</label>
                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1" class="control-label">Email</label>
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">NRIC</label>
                    @Html.EditorFor(model => model.NRIC, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.NRIC, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Age</label>
                    @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">ContactNo</label>
                    @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                </div>
                @*<div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Gender</label>
                    <div>
                        <label class="radio-inline">
                            @Html.RadioButtonFor(u => u.Gender, "Male", new { @class = "form-control", @checked = true, @id = "Male" })
                        </label> <label for="Male">Male</label>
                        <label class="radio-inline">
                            @Html.RadioButtonFor(u => u.Gender, "Female", new { @class = "form-control", @id = "Female" })
                        </label> <label for="Female">Female</label>
                    </div>
                </div>*@
                <div class="form-group">
                    <label for="exampleInputPassword1" class="control-label">Address</label>
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
                <div style="color:red">
                    @Html.ValidationSummary()
                </div>
                <button type="submit" class="btn btn-success waves-effect waves-light m-r-10">Save</button>
                @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success waves-effect waves-light m-r-10" })
            }
        </div>
    </div>
</div>

Views/ManageUsers/Index.cshtml
@model IEnumerable<HospitalManagament.User>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="white-box">

    <div class="table-responsive">
        <table id="myTable" class="table table-striped">
            <thead>
                <tr>
                    <th>FullName</th>
                    <th>Username</th>
                    <th>
                        Email
                    </th>
                    <th>
                        Last Login
                    </th>
                    <th>
                        IP Address
                    </th>
                    <th class="no-sort">
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UserName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LastLogin)
                        </td>
                        <td>
                            127.0.0.1
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                        </td>

                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

<script>
    $(document).ready(function () {
        $('#myTable').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'pdf', 'print'
            ]
        });

        $('.checkoutButton').click(function (e) {
            e.preventDefault();
            var _f = $(this).closest("form");

            $.post(_f.attr("action"), _f.serialize(), function (res) {
                //do something with the response coming back from your Save action method.
                if (res.status === "success") {
                    alert("Saved");
                    // If you want to reload the page, you can do this
                    //window.location.href = window.location.href;

                }
            });
        });
    });

</script>
<!--Style Switcher -->
<script src="../plugins/bower_components/styleswitcher/jQuery.style.switcher.js"></script>